const ActionTypes = {
    ADD_RECEIPT: 'ADD_RECEIPT',
    ADD_RECEIPT_SUCCESS: 'ADD_RECEIPT_SUCCESS',
    ADD_RECEIPT_FAIL: 'ADD_RECEIPT_FAIL',
    ADD: 'ADD',
    GETRECEIPT: 'GETRECEIPT',
    GETUSER: 'GETUSER',
    EDIT: "EDIT",
    SETADMINDATA: "SETADMINDATA",
    LOGIN: "LOGIN",
    SETSTUDENT: 'SETSTUDENT'
}

export default ActionTypes;
