const ActionTypes = {
    ADD: "ADD",
    SETDATA: "SETDATA",
    SETSTUDENT: 'SETSTUDENT',

    ADD_RECEIPT: 'ADD_RECEIPT',
    ADD_RECEIPT_SUCCESS: 'ADD_RECEIPT_SUCCESS',
    ADD_RECEIPT_FAIL: 'ADD_RECEIPT_FAIL',
}

export default ActionTypes